spring:
  datasource:
    url: jdbc:h2:mem:tetsdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console: true
    path: /console
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect